pipeline {
    agent any 
    stages {
        stage('Run Unit Tests') {
            steps {
                sh 'cd python-calculator'
                sh 'python3 calculator_unittest.py'
            }
        }
    }
}
